/* eslint-disable no-multi-spaces */
export App                      from './App/App';
export DevTools                 from './DevTools/DevTools';
export MainPageContainer        from './MainPageContainer/MainPageContainer';
export NewsPageContainer        from './NewsPageContainer/NewsPageContainer';
export ProjectPageContainer     from './ProjectPageContainer/ProjectPageContainer';
export AllNewsPageContainer     from './AllNewsPageContainer/AllNewsPageContainer';
export PageNotFound             from './PageNotFound/PageNotFound';
export AdminPageContainer       from './AdminPageContainer/AdminPageContainer';
export StaticPageContainer      from './StaticPageContainer/StaticPageContainer';
